#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "molokai"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    # enable_tabline_filetype_icon = false
    #   enable_statusline_mode = false
# statusline_unicode_symbols = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
#vimcompatible = true
    filemanager = "nerdtree"
    autocomplete_method = "coc"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "format"
  format_on_save = true

[[layers]]
  name = "denite"

[[layers]]
  name = "tmux"

[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 15

[[layers]]
  name = "tools"


[[layers]]
  name = "lang#python"
  python_interpreter = "/usr/local/opt/python/libexec/bin/python"

[[layers]]
  name = "lsp"


[[layers]]
  name = 'edit'
  autosave_timeout = 1000 
  autosave_all_buffers = true
  autosave_events = ['InsertLeave', 'TextChanged']

[[custom_plugins]]
  name = 'chrisbra/Colorizer'
  merged = false


[[custom_plugins]]
  name = 'Exafunction/codeium.vim'
  merged = false
